[workspace]

members = [
  # Tooling
  "cli",
  "development_server",

  # Services
  "services/function",

  # Guests
  "guests/function",
]

resolver= "2"

[workspace.dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
