[target.x86_64-unknown-linux-gnu]
image = "rustembedded/cross:x86_64-unknown-linux-gnu"
# pre-build = [
#   "dpkg --add-architecture $CROSS_DEB_ARCH",
#   "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH",
# ]


[target.x86_64-pc-windows-gnu]
image = "rustembedded/cross:x86_64-pc-windows-gnu"

# FIXME: these are giving manifest errors.
# Can be built local (w/ Rosetta) on Mac OS M1's though

# [target.x86_64-apple-darwin]
# image = "freeznet/x86_64-apple-darwin-cross"

# [target.aarch64-apple-darwin]
# image = "eeznet/aarch64-apple-darwin-cross"
