package mycelia:execution@0.0.1

interface function-interface {
  record foo-bar {
    name: string,
  }
}

world function-world {
  use function-interface.{foo-bar}


  resource cool {
    constructor()
    name: func() -> string
  }

  export init: func()
  export test: func(v : foo-bar) -> string
  export test-resource: func(v : cool) -> string
}
