[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap-cargo = "0.12.0"
clap = { version = "4.4.2", features = ["derive"] }
development_server = { path = "../development_server" }
