name: Rust Build

on:
  push:
    branches: [dani_replace_xtask_by_cli]
  pull_request:
    branches: [dani_replace_xtask_by_cli]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          # - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
          # - x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v2

      - name: Set up a Rust toolchain
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          rustup target add wasm32-wasi
          sudo apt-get install -y pkg-config libssl-dev protobuf-compiler
          cargo install wasm-tools
      - name: Build for target
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: build ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/
