name: Rust
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            x86_64-pc-windows-gnu,
            x86_64-unknown-linux-musl,
            x86_64-apple-darwin,
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up a Rust toolchain
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.4
        with:
          RUSTTARGET: ${{ matrix.target }}
          SRC_DIR: cli
          ARCHIVE_TYPES: zip targ.gz
      - name: Tar compiled binaries
        uses: a7ul/tar-action@v1.1.3
        with:
          cwd: ${{ steps.compile.outputs.BUILT_BINARY }}
          command: c
          files: ${{ steps.compile.outputs.BUILT_BINARY }}
          outPath: binaries.tar.gz
      - name: Commit and push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add binaries.tar.gz
          git commit -m 'Add compiled binaries'
          git push
